default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: postgres
  password: root

development:
  <<: *default
  database: rar_development

test:
  <<: *default
  database: rar_test
